version: '3.8'

services:
  backend:
    build: .
    container_name: chat-app-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    command: npm start

  mongo:
    image: mongo:6
    container_name: chat-app-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
